var manifest = [
    {
        src:"lib/Sprites.json",
        forSpritesheet:"Sprites"
    },
    {
        src:"lib/Sprites.png",
        id:"Sprites"
    },
    {
        src:"lib/explosion.ogg",
        id:"explosion",
        data:4,
    },
    {
        src:"lib/firing.ogg",
        id:"shot",
        data:4
    },
    {
        src:"lib/Laser.ogg",
        id:"laser",
        data:4
    },
    {
        src:"lib/Roar.ogg",
        id:"roar",
        data:4
    },
    {
        src:"lib/explosion2.ogg",
        id:"explosion2",
        data:4
    },
    
    {
        src:"lib/spawn.ogg",
        id:"spawn",
        data:4
    }
];